version: '3.9'

services:
  mariadb:
    image: mariadb:11.7.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mojadb
      MYSQL_USER: user123
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command:
      --slow_query_log=1
      --slow_query_log_file=/var/log/mysql/slow.log
      --long_query_time=1
      --log_output=FILE

volumes:
  mariadb_data: 